In [12]:
import numpy as np
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

digits=load_digits()


In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [14]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

AttributeError: 'str' object has no attribute 'decode'

In [19]:
svc=SVC()
svc.fit(x_train,y_train)
svc.score(x_test,y_test)

0.9925925925925926

In [22]:
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)
rfc.score(x_test,y_test)

0.9740740740740741

In [24]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [30]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [31]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [32]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9925925925925926

In [ ]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [38]:
score_scv=[]
score_rfc=[]

for train_index, test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],\
                                  digits.target[train_index],digits.target[test_index]
    score_scv.append(get_score(svc,x_train,x_test,y_train,y_test))
    score_rfc.append(get_score(rfc,x_train,x_test,y_train,y_test))
score_scv


[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [39]:
score_rfc

[0.9282136894824707, 0.9616026711185309, 0.9282136894824707]

In [40]:
#short version
from sklearn.model_selection import cross_val_score

In [41]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.93055556, 0.90833333, 0.96935933, 0.96657382, 0.92200557])

In [42]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])