In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [10]:
df=pd.read_csv('homeprices.csv')

In [11]:
# distirbution is suitable for limnear model
model=linear_model.LinearRegression()
model.fit(df[['area']],df['price'])

LinearRegression()

In [12]:
model.coef_

array([167.30954677])

In [13]:
model.intercept_

76692.3818707813

In [14]:
import pickle

In [15]:
#saving your model for using later
with open('model_pickel','wb')as f:
    pickle.dump(model,f)

In [18]:
#loading the model
with open('model_pickel','rb') as f:
    mp=pickle.load(f)

In [19]:
mp.predict([[3000]])

array([578621.02217936])

In [22]:
from joblib import dump, load

In [24]:
cd=dump(model,'model_joblib')

In [25]:
mb=load('model_joblib')

In [26]:
mb.predict([[5000]])

array([913240.11571842])